cart/urls.py
# coding: utf-8
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

coupons/urls.py
# coding: utf-8
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^apply/$', views.coupon_apply, name='apply'),
]

myshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^coupon/', include('coupons.urls', namespace='coupons')),
    url(r'^', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
# coding: utf-8

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$',
        views.order_create,
        name='order_create'),
    url(r'^admin/order/(?P<order_id>\d+)/$', views.admin_order_detail, name='order_detail'),
    url(r'^admin/order/(?P<order_id>\d+)/pdf/$', views.create_pdf, name='create_pdf'),
]

shop/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

cart/forms.py
# coding: utf-8

from django import forms

PRODUCT_QUALITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddForm(forms.Form):
    """
    展现一个购物车表单。
    """
    # 限定取值范围在1-20之间
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUALITY_CHOICES,
        coerce=int
    )
    # 是否为更新值？？和Cart类中的update相关。后期补充作用。
    update = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )

cart/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddForm
from coupons.forms import CouponApplyForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quality=cd['update'])
    return redirect("cart:cart_detail")


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddForm(
            initial={'quantity': item['quantity'],
                     'update': True}
        )
    coupon_form = CouponApplyForm()
    return render(request, 'cart/detail.html', {'cart': cart,
                                                'coupon_form': coupon_form})

# Create your views here.

cart/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
U shopping cart
{% endblock %}

{% block content %}
<h1>Your shopping cart</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit Price</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with item.product as product %}
            <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}">
                        <img src="
                        {% if product.image %}
                            {{ product.image.url }}
                        {% else %}
                            {% static 'img/no_image.png' %}
                        {% endif %}
                        " alt="">
                    </a>
                </td>
                <td>{{ product.name }}</td>
                <td>
                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                        {{ item.update_quantity_form.quantity }}
                        {{ item.update_quantity_form.update }}
                        <input type="submit" value="Update">
                        {% csrf_token %}
                    </form>
                </td>
                <td><a href="{% url 'cart:cart_remove' product.id %}">Remove</a></td>
                <td class="num">￥{{ item.price }}</td>
                <td class="num">￥{{ item.total_price }}</td>
            </tr>
            {% endwith %}
            {% endfor %}
            {% if cart.coupon %}
                <tr class="subtotal">
                    <td>Subtotal</td>
                    <td colspan="4"></td>
                    <td class="num">￥{{ cart.get_total_price }}</td>
                </tr>
                <tr>
                    <td>'{{ cart.coupon.code }}' Coupon ({{ cart.coupon.discount }} off)</td>
                    <td colspan="4"></td>
                    {% if cart.get_discount %}
                        <td class="num neg">- ￥{{ cart.get_discount }}</td>
                    {% endif %}
                </tr>
            {% endif %}
            <tr class="total">
                <td>Total</td>
                <td colspan="4"></td>
                <td class="num">
                ${{ cart.get_total_price_after_discount|floatformat:"2" }}
                </td>
            </tr>
        </tbody>
    </table>
    <p>Apply a coupon:</p>
    <form action="{% url "coupons:apply" %}" method="post">
        {{ coupon_form }}
        <input type="submit" value="Apply">
        {% csrf_token %}
    </form>
    <p class="text-right">
        <a href="{% url 'shop:product_list' %}" class="button light">Continue shopping</a>
        <a href="{% url 'orders:order_create' %}" class="button">Checkout</a>
    </p>
{% endblock %}